"""
Schema Definitions Module

This module defines the primary data structures used to hold the state 
across the entire lifecycle of the Kaggle Copilot workflow. It uses Pydantic 
for strict typing and easy serialization.
"""

from pydantic import BaseModel, Field

class KaggleState(BaseModel):
    """
    The Single Source of Truth (SSOT) state object for the workflow.
    
    This state gets passed between all agents and nodes. As the workflow progresses,
    different nodes append or overwrite specific fields in this state.
    
    Attributes:
        input_text: The initial user input (usually a Kaggle competition URL).
        dataset_characteristics: High-level overview of the dataset extracted from metadata/EDA.
        problem_type_patterns: The identified ML problem type (e.g., binary classification) and objectives.
        preprocessing_strategy: Human-readable explanation of the data preprocessing plan.
        preprocessing_code: Executable Python code (scikit-learn/pandas) for preprocessing.
        feature_engineering_strategy: Human-readable explanation of feature engineering techniques.
        feature_engineering_code: Executable Python code for creating new features.
        baseline_strategies: Human-readable explanation of the selected model architectures and training approach.
        baseline_code: Executable Python code defining the model(s) and training process.
        evaluation_code: Executable Python code for evaluating model performance (e.g., cross-validation).
        final_script: The complete, runnable Python script combining all code snippets.
        human_feedback: Feedback provided by the user during the interactive review phase.
        final_report: The complete Markdown report explaining the entire approach.
        critic_feedback: Automatic feedback generated by the code_critic_node to catch common pitfalls.
        final_notebook: The raw JSON string of the final Jupyter Notebook (.ipynb).
        research_sources: Formatted markdown string containing links to web sources consulted by the research agent.
    """
    input_text: str = ""
    dataset_characteristics: str = ""
    problem_type_patterns: str = ""
    preprocessing_strategy: str = ""
    preprocessing_code: str = ""
    feature_engineering_strategy: str = ""
    feature_engineering_code: str = ""
    baseline_strategies: str = ""
    baseline_code: str = ""
    evaluation_code: str = ""
    final_script: str = ""
    human_feedback: list[str] = Field(default_factory=list)
    final_report: str = ""
    critic_feedback: str = ""
    final_notebook: str = ""
    research_sources: str = ""
